management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /

logging:
  level:
    org.cgi.assesment: debug
server:
  servlet:
    contextPath: /order-management-service
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    name: cgi
    username: sa
    password: sa
    url: jdbc:h2:mem:eriks-digital
